name: Setup Python with uv
description: Install uv, set up Python, and install project dependencies

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      shell: bash
      run: uv python install

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
